/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package m03_act_13_concesionario;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor Mendes Ceballos
 */
public class GestionVehiculos extends javax.swing.JFrame {
    
    private HashMap<String, Vehiculo> vehiculos = new HashMap<>();

    /**
     * Creates new form GestionVehiculos
     */
    public GestionVehiculos() {
        initComponents();
        setTitle("Gestión de Vehículos");   //Título 
        setSize(450, 290);                  // Tamaño  de la ventana
        setLocationRelativeTo(null);        // Centra la ventana en la pantalla
        setResizable(false);                // Evita que se redimensione
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setLabel("Ingresar Vehículo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar Moto o Coche");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar Coches");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar Motos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // Eliminar un vehículo
    
    // Preguntamos el tipo de vehículo a eliminar
    int tipo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el tipo de vehículo que desea eliminar (1: moto; 2: coche):"));

    // Construimos una lista de los vehículos de ese tipo
    StringBuilder lista = new StringBuilder("Listado de vehículos:\n");
    for (Vehiculo v : vehiculos.values()) {
        if (v.getTipo() == tipo) {
            lista.append("Matrícula: ").append(v.getMatricula()).append(" - ").append(v.getModelo()).append("\n");
        }
    }

    // Mostramos el listado
    JOptionPane.showMessageDialog(this, lista.toString());

    // Pedimos la matrícula a eliminar
    String matricula = JOptionPane.showInputDialog(this, "Ingrese la matrícula del vehículo que desea eliminar:");

    // Verificamos si existe
    Vehiculo eliminado = vehiculos.remove(matricula);

    // Mostramos el resultado
    if (eliminado != null) {
        JOptionPane.showMessageDialog(this, "Vehículo eliminado correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró un vehículo con esa matrícula.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Ingresar un nuevo vehículo

    // Pedimos los datos al usuario
    String matricula = JOptionPane.showInputDialog(this, "Ingrese la matrícula del vehículo:");
    String marca = JOptionPane.showInputDialog(this, "Ingrese la marca del vehículo:");
    String modelo = JOptionPane.showInputDialog(this, "Ingrese el modelo del vehículo:");

    int cilindrada = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la cilindrada del vehículo:"));
    double precio = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese el precio del vehículo:"));
    int tipo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el tipo de vehículo (1: moto; 2: coche):"));

    // Creamos una lista vacía de complementos (por ahora no se piden)
    ArrayList<String> complementos = new ArrayList<>();

    // Creamos el objeto Vehiculo con los datos introducidos
    Vehiculo nuevo = new Vehiculo(matricula, marca, modelo, cilindrada, complementos, precio, tipo);

    // Insertamos en el HashMap usando la matrícula como clave
    vehiculos.put(matricula, nuevo);

    // Confirmación
    JOptionPane.showMessageDialog(this, "Vehículo registrado correctamente.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // Mostrar coche

    // Mostramos solo los vehículos que sean coches (tipo 2)
    StringBuilder listaCoches = new StringBuilder("Listado de coches:\n");

    for (Vehiculo v : vehiculos.values()) {
        if (v.getTipo() == 2) {
            listaCoches.append("Matrícula: ").append(v.getMatricula())
                       .append(" - ").append(v.getModelo()).append("\n");
        }
    }

    JOptionPane.showMessageDialog(this, listaCoches.toString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // Mostrar moto
    
    // Mostramos solo los vehículos que sean motos (tipo 1)
    StringBuilder listaMotos = new StringBuilder("Listado de motos:\n");

    for (Vehiculo v : vehiculos.values()) {
        if (v.getTipo() == 1) {
            listaMotos.append("Matrícula: ").append(v.getMatricula())
                      .append(" - ").append(v.getModelo()).append("\n");
        }
    }

    JOptionPane.showMessageDialog(this, listaMotos.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    // Salir
    
    // Cerramos la aplicación
    System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
